name: 'Amplify Deploy'
on:
  push:
    branches: [ main ]
jobs:
  test:
    name: test amplify-cli-action
    env:
      awsregion: us-east-1
      amplifyversion: 4.16.1
      amplifyenvironment: staging
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1

    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: install amplify command for pull the appID 
      run: |
        curl -sL https://aws-amplify.github.io/amplify-cli/install | bash && $SHELL
        /usr/bin/amplify pull --appId d165re0xa92lmj --envName staging

    - name: configure amplify
      uses: ambientlight/amplify-cli-action@0.3.0
      with:
        amplify_cli_version: ${{ env.amplifyversion }}
        amplify_command: configure
        amplify_env: staging
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1

    - name: install, build and test
      run: |
        npm install
        npm test
        npm build
        # build and test
        # npm run build
        # npm run test
        

    
    - name: deploy
      uses: ambientlight/amplify-cli-action@0.3.0
      with:
        amplify_cli_version: ${{ env.amplifyversion }}
        amplify_command: publish
        amplify_env: staging
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
    
        
        
